// SPDX-License-Identifier: CC0-1.0

import js from '@eslint/js';

const gjsGlobals = {
    ARGV: 'readonly',
    TextDecoder: 'readonly',
    TextEncoder: 'readonly',
    console: 'readonly',
    global: 'readonly',
    log: 'readonly',
    logError: 'readonly',
    print: 'readonly',
    printerr: 'readonly',
};

export default [
    {
        ignores: [
            'build/**',
            'netbird-gnome-old/**',
            'node_modules/**',
            'screenshots/**',
        ],
    },
    js.configs.recommended,
    {
        files: ['**/*.js'],
        languageOptions: {
            globals: gjsGlobals,
            parserOptions: {
                ecmaVersion: 2022,
                sourceType: 'module',
            },
        },
        rules: {
            'array-bracket-newline': ['error', 'consistent'],
            'array-bracket-spacing': ['error', 'never'],
            'array-callback-return': 'error',
            'arrow-parens': ['error', 'as-needed'],
            'arrow-spacing': 'error',
            'block-scoped-var': 'error',
            'block-spacing': 'error',
            'brace-style': ['error', '1tbs'],
            'comma-dangle': ['error', {
                arrays: 'always-multiline',
                exports: 'always-multiline',
                functions: 'never',
                imports: 'always-multiline',
                objects: 'always-multiline',
            }],
            'comma-spacing': 'error',
            'comma-style': ['error', 'last'],
            'computed-property-spacing': 'error',
            'curly': ['error', 'multi-or-nest', 'consistent'],
            'dot-location': ['error', 'property'],
            'eol-last': 'error',
            'eqeqeq': 'error',
            'func-call-spacing': 'error',
            'func-name-matching': 'error',
            'indent': ['error', 4, {
                ignoredNodes: [
                    'CallExpression[callee.object.name=GObject]' +
                        '[callee.property.name=registerClass] > ClassExpression',
                ],
            }],
            'key-spacing': 'error',
            'keyword-spacing': 'error',
            'linebreak-style': ['error', 'unix'],
            'lines-between-class-members': ['error', 'always', {
                exceptAfterSingleLine: true,
            }],
            'max-len': ['error', {
                code: 100,
                ignoreComments: true,
                ignoreStrings: true,
                ignoreTemplateLiterals: true,
                ignoreUrls: true,
            }],
            'max-statements-per-line': 'error',
            'new-parens': 'error',
            'no-array-constructor': 'error',
            'no-await-in-loop': 'error',
            'no-caller': 'error',
            'no-constant-binary-expression': 'error',
            'no-constructor-return': 'error',
            'no-empty': ['error', {allowEmptyCatch: true}],
            'no-extend-native': 'error',
            'no-extra-bind': 'error',
            'no-extra-parens': ['error', 'all', {
                conditionalAssign: false,
                nestedBinaryExpressions: false,
                returnAssign: false,
            }],
            'no-iterator': 'error',
            'no-label-var': 'error',
            'no-loop-func': 'error',
            'no-multiple-empty-lines': ['error', {max: 1, maxEOF: 0}],
            'no-new-native-nonconstructor': 'error',
            'no-new-object': 'error',
            'no-new-wrappers': 'error',
            'no-promise-executor-return': 'error',
            'no-proto': 'error',
            'no-restricted-globals': [
                'error',
                {message: 'Use console methods instead', name: 'log'},
                {message: 'Use console methods instead', name: 'logError'},
            ],
            'no-return-assign': 'error',
            'no-self-compare': 'error',
            'no-shadow': ['error', {ignoreOnInitialization: true}],
            'no-template-curly-in-string': 'error',
            'no-throw-literal': 'error',
            'no-trailing-spaces': 'error',
            'no-undef-init': 'error',
            'no-unmodified-loop-condition': 'error',
            'no-unneeded-ternary': 'error',
            'no-unreachable-loop': 'error',
            'no-unused-private-class-members': 'error',
            'no-unused-vars': ['error', {
                argsIgnorePattern: '^_',
                varsIgnorePattern: '^_',
            }],
            'no-use-before-define': ['error', {
                allowNamedExports: true,
                classes: false,
                functions: false,
                variables: true,
            }],
            'no-var': 'error',
            'no-whitespace-before-property': 'error',
            'object-curly-newline': ['error', {
                consistent: true,
                multiline: true,
            }],
            'object-curly-spacing': ['error', 'never'],
            'object-shorthand': 'error',
            'operator-assignment': 'error',
            'operator-linebreak': ['error', 'after', {
                overrides: {
                    ':': 'before',
                    '?': 'before',
                },
            }],
            'padded-blocks': ['error', 'never'],
            'prefer-const': 'error',
            'prefer-numeric-literals': 'error',
            'prefer-promise-reject-errors': 'error',
            'prefer-rest-params': 'error',
            'prefer-spread': 'error',
            'prefer-template': 'error',
            'quotes': ['error', 'single', {avoidEscape: true}],
            'rest-spread-spacing': 'error',
            'semi': ['error', 'always'],
            'semi-spacing': 'error',
            'space-before-blocks': 'error',
            'space-before-function-paren': ['error', {
                anonymous: 'always',
                asyncArrow: 'always',
                named: 'never',
            }],
            'space-in-parens': ['error', 'never'],
            'space-infix-ops': 'error',
            'space-unary-ops': 'error',
            'spaced-comment': 'error',
            'template-curly-spacing': 'error',
            'unicode-bom': 'error',
            'yoda': 'error',
        },
    },
    {
        files: ['netbird/transport.js'],
        rules: {
            // Socket and framing reads are necessarily sequential.
            'no-await-in-loop': 'off',
        },
    },
    {
        files: ['tests/**/*.js'],
        rules: {
            // Integration fixtures intentionally run stateful operations in order.
            'no-await-in-loop': 'off',
            'no-use-before-define': ['error', {
                allowNamedExports: true,
                classes: false,
                functions: false,
                variables: true,
            }],
        },
    },
];
